project:
  type: website

website:
  title: "Q Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      
format:
  html:
    theme: cosmo
    html-math-method: mathjax
    code-fold: show
    


