project:
  type: website

website:
  title: "Q Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    code-tools: true
    code-fold: show
    code-overflow: wrap
    code-line-numbers: true
    html-math-method: mathjax
    


