project:
  type: website

website:
  title: "Q Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      
format:
  html:
    theme: cosmo
    html-math-method: mathjax
    include-in-header: 
      text: |
        <script>
        window.MathJax = {
          tex: {
            inlineMath: [['$', '$'], ['\\(', '\\)']],
            displayMath: [['$$', '$$'], ['\\[', '\\]']]
          }
        };
        </script>
    code-fold: show
    


